# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36014a3d370092f4bebc4c6a9e82b4bbf474dbe693231a50cc0d2a0ce662a127ec587e111a8ba259728e93b2471379e6348e05dc17d61a249fe1b5c21f052819

test:
  secret_key_base: 772c26b34aef7b6e2fe1ea0216089398beae4f557697e59bdc96e6d3988e3ebb96acf1a5eb9a5aefdd4c9b2b7deddb92169b7ea547e039eea06a1eaa26d06c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
